/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/csrf-attack-defense': RouteRecordInfo<'/posts/csrf-attack-defense', '/posts/csrf-attack-defense', Record<never, never>, Record<never, never>>,
    '/posts/diy-markdown-visit-counter': RouteRecordInfo<'/posts/diy-markdown-visit-counter', '/posts/diy-markdown-visit-counter', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/oauth2-authentication-implementation': RouteRecordInfo<'/posts/oauth2-authentication-implementation', '/posts/oauth2-authentication-implementation', Record<never, never>, Record<never, never>>,
    '/posts/sophgo-runtime-setup': RouteRecordInfo<'/posts/sophgo-runtime-setup', '/posts/sophgo-runtime-setup', Record<never, never>, Record<never, never>>,
    '/posts/spring-aop-deep-dive': RouteRecordInfo<'/posts/spring-aop-deep-dive', '/posts/spring-aop-deep-dive', Record<never, never>, Record<never, never>>,
    '/posts/web-authentication-methods': RouteRecordInfo<'/posts/web-authentication-methods', '/posts/web-authentication-methods', Record<never, never>, Record<never, never>>,
    '/posts/web-authorization-methods': RouteRecordInfo<'/posts/web-authorization-methods', '/posts/web-authorization-methods', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
