/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/about-microservices-and-cloudnative': RouteRecordInfo<'/posts/about-microservices-and-cloudnative', '/posts/about-microservices-and-cloudnative', Record<never, never>, Record<never, never>>,
    '/posts/build-ai-assistant-using-rag': RouteRecordInfo<'/posts/build-ai-assistant-using-rag', '/posts/build-ai-assistant-using-rag', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/java-jit-and-aot': RouteRecordInfo<'/posts/java-jit-and-aot', '/posts/java-jit-and-aot', Record<never, never>, Record<never, never>>,
    '/posts/jvm-class-loading-deep-dive': RouteRecordInfo<'/posts/jvm-class-loading-deep-dive', '/posts/jvm-class-loading-deep-dive', Record<never, never>, Record<never, never>>,
    '/posts/jvm-memory-gc-deep-dive': RouteRecordInfo<'/posts/jvm-memory-gc-deep-dive', '/posts/jvm-memory-gc-deep-dive', Record<never, never>, Record<never, never>>,
    '/posts/redis-data-structures': RouteRecordInfo<'/posts/redis-data-structures', '/posts/redis-data-structures', Record<never, never>, Record<never, never>>,
    '/posts/redis-hyperloglog': RouteRecordInfo<'/posts/redis-hyperloglog', '/posts/redis-hyperloglog', Record<never, never>, Record<never, never>>,
    '/posts/sophgo-runtime-setup': RouteRecordInfo<'/posts/sophgo-runtime-setup', '/posts/sophgo-runtime-setup', Record<never, never>, Record<never, never>>,
    '/posts/web-authentication-methods': RouteRecordInfo<'/posts/web-authentication-methods', '/posts/web-authentication-methods', Record<never, never>, Record<never, never>>,
    '/posts/web-authorization-methods': RouteRecordInfo<'/posts/web-authorization-methods', '/posts/web-authorization-methods', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
